### PR TITLE
Return the body of a Redirect Response.

### PR DESCRIPTION
**Pull request by l-dobrev**
Attempt to fix issue #70 by forwarding the body of a redirect response.

### CODE REVIEW

**Comment by dsmiley** [comment]
Maybe I merged the other PR #71 prematurely.  I'm now wondering... perhaps doResponseRedirectOrNotModifiedLogic could be removed entirely, and instead copyResponseHeaders could rewrite the LOCATION header -- and that's it.  No monkeying with content-length.  If there is a response body then return it to the client, if there isn't then don't.  What do you think?

**Comment by l-dobrev** [comment]
Well, I believed the #72 is superior to #71.
When creating both #71 and #72 I was aiming to produce as little change as possible, so removing methods (protected, possibly overridden by subclasses) was inadmissible.
The solution you propose does seem much better, and much cleaner. I'm however reluctant to introduce API incompatibilities. If you're OK with that though I can try and provide a third way to resolve the issue following your guidance.

**Comment by dsmiley** [comment]
It's definitely okay to change the class signature (e.g. removing protected methods).  The main constraint I'm sticking with is to keep this a simple single class-file implementation.

**Comment by dsmiley** [comment]
Closing; implemented by #73

**Pull request closed without merging**
