### PR TITLE
%5B %5D should be encoded

### PR DESCRIPTION
**Pull request by phuongnq**
https://github.com/mitre/HTTP-Proxy-Servlet/issues/215

### CODE REVIEW

**Comment by dsmiley** [comment]
Thanks for fixing this and quoting the RFC!  I don't quite understand the test change but I didn't look at it long.
Can you add an entry to `CHANGES.md` crediting yourself for this for the latest version?

**Comment by dsmiley** [comment]
Ah; I read #215 .  This isn't really a test (unless I'm forgetting my code; could be).  If you don't think it's possible to test this; I could look closer.

**Comment by phuongnq** [comment]
I updated `CHANGES.md`. Yes, it's not actually a new test case. I just updated it so that the base includes some special characters. If you think this should be updated. Please go ahead or let me know.

Thank you for looking at the issue!

**Comment by dsmiley** [comment]
See testProxyWithUnescapedChars.  Try adding a new line with these chars and ensure they get escaped.  So just a one-liner I hope.  Revert your change to the previous test.

**Comment by phuongnq** [comment]
@dsmiley I added the test case add noted.

**Pull request merged**
