### PR TITLE
Class provides a connection to a system which handles client authentication with a certificate

### PR DESCRIPTION
**Pull request by ctornau**
An extension to the proxy library which enables the user to connect to a backend service which authenticates the proxy through a client certificate. 

It has to be configured the following way:

```xml
<init-param>
   <param-name>keystore</param-name>
   <param-value>keystorecontainingcertificate.keystore</param-value>
</init-param>
<init-param>
   <param-name>keystorepassword</param-name>
   <param-value>thePassword</param-value>
</init-param>
```

### CODE REVIEW

**Comment by dsmiley** [comment]
Cool.  I don't think I'm ready to commit this yet.  On the #61 branch I've got SNI/SSL support and I had to break support for older versions insofar as testing.  That branch supports as far back as 4.3.  I stalled on that because it wasn't tested and nor is this for that matter.  I'm thinking of labelling them in comments as "EXPERIMENTAL", and furthermore forgoing supporting older HttpProxy versions in testing.

**Comment by ctornau** [comment]
Hi David,

is it possible to have a main version which supports old HTTP-CLIENT versions and a new version which supports SSL? It would be great if the new features will be also available as Maven imports.

**Comment by dsmiley** [comment]
Yes. And I think a new major version would be good to establish that, with a branch, or at least branch off the current for legacy. Nonetheless it'd be a shame to not test this in some way. FYI I'm on vacation until 25th, so I won't be doing anything until then.

**Comment by ctornau** [comment]
I already tested this with a certificate here against an Apache HTTP Server (non Java stuff). However I agree that an automatic test executable by the CI would be great.

**Comment by dsmiley** [comment]
Did you close this simply because it hasn't been merged/committed yet?  If so I suggest re-opening; I may merge this yet.  No promises on the timing :-)

**Pull request closed without merging**
