### PR TITLE
Fix encoding of % in request path

### PR DESCRIPTION
**Pull request by splintor**

### CODE REVIEW

**Comment by dsmiley** [comment]
This is a bit confusing to me but I think I get it finally.  I think it would be clearer if encodeUriQuery had a `boolean encodePct` param, and then you could pass true for the path part, and false for the queryString part (and I guess fragment as well).  This would at least make this more explicit, I think.

**Comment by splintor** [comment]
@dsmiley Sounds good., I made the change you suggested - please review and merge (and release...)

**Comment by splintor** [comment]
Thanks. Any idea about the next release date?

**Comment by dsmiley** [comment]
I just pushed a new release -- 1.10.  Let me know if there are any issues.  Thanks.

**Pull request merged**
